name: Labeler

on:
  push:
    branches:
      - main
      - master

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-delete: true
